server:
  port: 8848

spring:
  activemq:
    broker-url: nio://localhost:61608 #mq server tcp://localhost:61616
    user: admin
    password: admin
  jms:
    pub-sub-domain: false # false=queue  true=topic default is false

myqueue: boot-activemq-queue